// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlIVgDE1prB9l3pRXiMzR_2txSAMyGkU4',
    appId: '1:316807487054:web:5eeb4be291b6fad846ed1f',
    messagingSenderId: '316807487054',
    projectId: 'eventi-85fb2',
    authDomain: 'eventi-85fb2.firebaseapp.com',
    storageBucket: 'eventi-85fb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbDt9r60NWHwFYKSMp8sBgOTGDvpJJ62I',
    appId: '1:316807487054:android:42bddbb5f5c31a6d46ed1f',
    messagingSenderId: '316807487054',
    projectId: 'eventi-85fb2',
    storageBucket: 'eventi-85fb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLRfCqfF3cZc-A-SO2d2gO3iuGPSXw2tg',
    appId: '1:316807487054:ios:15697293f8725e6746ed1f',
    messagingSenderId: '316807487054',
    projectId: 'eventi-85fb2',
    storageBucket: 'eventi-85fb2.appspot.com',
    iosClientId: '316807487054-uujhih488iv57eoehpg231aobh1qr5f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.authent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLRfCqfF3cZc-A-SO2d2gO3iuGPSXw2tg',
    appId: '1:316807487054:ios:15697293f8725e6746ed1f',
    messagingSenderId: '316807487054',
    projectId: 'eventi-85fb2',
    storageBucket: 'eventi-85fb2.appspot.com',
    iosClientId: '316807487054-uujhih488iv57eoehpg231aobh1qr5f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.authent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlIVgDE1prB9l3pRXiMzR_2txSAMyGkU4',
    appId: '1:316807487054:web:1139931d30c4e03846ed1f',
    messagingSenderId: '316807487054',
    projectId: 'eventi-85fb2',
    authDomain: 'eventi-85fb2.firebaseapp.com',
    storageBucket: 'eventi-85fb2.appspot.com',
  );
}
